// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MENU1_H
#define UI_MENU1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Menu1
extern void ui_Menu1_screen_init(void);
extern void ui_Menu1_screen_destroy(void);
extern lv_obj_t * ui_Menu1;
extern lv_obj_t * ui_MenuPrev;
extern lv_obj_t * ui_MenuPrevRoller;
extern lv_obj_t * ui_MenuActive;
extern lv_obj_t * ui_MenuActiveRoller;
extern lv_obj_t * ui_MenuNext;
extern lv_obj_t * ui_MenuNextRoller;
extern lv_obj_t * ui_ButtonIcons2;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

