// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Menu1 = NULL;
lv_obj_t * ui_MenuPrev = NULL;
lv_obj_t * ui_MenuPrevRoller = NULL;
lv_obj_t * ui_MenuActive = NULL;
lv_obj_t * ui_MenuActiveRoller = NULL;
lv_obj_t * ui_MenuNext = NULL;
lv_obj_t * ui_MenuNextRoller = NULL;
lv_obj_t * ui_ButtonIcons2 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Button7 = NULL;
// event funtions

// build funtions

void ui_Menu1_screen_init(void)
{
    ui_Menu1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Menu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Menu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuPrev = lv_obj_create(ui_Menu1);
    lv_obj_remove_style_all(ui_MenuPrev);
    lv_obj_set_width(ui_MenuPrev, 341);
    lv_obj_set_height(ui_MenuPrev, 438);
    lv_obj_set_x(ui_MenuPrev, -800);
    lv_obj_set_y(ui_MenuPrev, 0);
    lv_obj_set_align(ui_MenuPrev, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_MenuPrev, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuPrevRoller = lv_roller_create(ui_MenuPrev);
    lv_roller_set_options(ui_MenuPrevRoller, "Option1\nOption2\nOption3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_MenuPrevRoller, 396);
    lv_obj_set_width(ui_MenuPrevRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MenuPrevRoller, 0);
    lv_obj_set_y(ui_MenuPrevRoller, -26);
    lv_obj_set_align(ui_MenuPrevRoller, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_MenuPrevRoller, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_MenuPrevRoller, LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_text_color(ui_MenuPrevRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuPrevRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MenuPrevRoller, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuPrevRoller, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuPrevRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuPrevRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuPrevRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuPrevRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_MenuPrevRoller, &ui_font_Bold, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuPrevRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuPrevRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_MenuActive = lv_obj_create(ui_Menu1);
    lv_obj_remove_style_all(ui_MenuActive);
    lv_obj_set_width(ui_MenuActive, 341);
    lv_obj_set_height(ui_MenuActive, 438);
    lv_obj_set_align(ui_MenuActive, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_MenuActive, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuActiveRoller = lv_roller_create(ui_MenuActive);
    lv_roller_set_options(ui_MenuActiveRoller, "Menu1\nMenu2\nMenu3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_MenuActiveRoller, 396);
    lv_obj_set_width(ui_MenuActiveRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MenuActiveRoller, 8);
    lv_obj_set_y(ui_MenuActiveRoller, -26);
    lv_obj_set_align(ui_MenuActiveRoller, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_MenuActiveRoller, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_MenuActiveRoller, LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_text_color(ui_MenuActiveRoller, lv_color_hex(0x818181), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuActiveRoller, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MenuActiveRoller, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuActiveRoller, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuActiveRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuActiveRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuActiveRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuActiveRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_MenuActiveRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuActiveRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuActiveRoller, &ui_font_Bold, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuActiveRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuActiveRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_MenuNext = lv_obj_create(ui_Menu1);
    lv_obj_set_width(ui_MenuNext, 281);
    lv_obj_set_height(ui_MenuNext, 261);
    lv_obj_set_x(ui_MenuNext, 800);
    lv_obj_set_y(ui_MenuNext, 0);
    lv_obj_set_align(ui_MenuNext, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_MenuNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuNext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuNext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuNextRoller = lv_roller_create(ui_MenuNext);
    lv_roller_set_options(ui_MenuNextRoller, "Option1\nOption2\nOption3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_MenuNextRoller, 396);
    lv_obj_set_width(ui_MenuNextRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MenuNextRoller, 0);
    lv_obj_set_y(ui_MenuNextRoller, -26);
    lv_obj_set_align(ui_MenuNextRoller, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuNextRoller, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_MenuNextRoller, LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_text_color(ui_MenuNextRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuNextRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MenuNextRoller, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuNextRoller, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuNextRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuNextRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuNextRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuNextRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(ui_MenuNextRoller, LV_TEXT_ALIGN_LEFT, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuNextRoller, &ui_font_Bold, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuNextRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuNextRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ButtonIcons2 = lv_obj_create(ui_Menu1);
    lv_obj_remove_style_all(ui_ButtonIcons2);
    lv_obj_set_width(ui_ButtonIcons2, 800);
    lv_obj_set_height(ui_ButtonIcons2, 60);
    lv_obj_set_align(ui_ButtonIcons2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ButtonIcons2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonIcons2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ButtonIcons2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button9 = lv_btn_create(ui_ButtonIcons2);
    lv_obj_set_width(ui_Button9, 50);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button9, &ui_img_arrowup_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_ButtonIcons2);
    lv_obj_set_width(ui_Button5, 50);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button5, &ui_img_arrowdown_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_ButtonIcons2);
    lv_obj_set_width(ui_Button6, 50);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button6, &ui_img_backarrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_ButtonIcons2);
    lv_obj_set_width(ui_Button7, 50);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button7, &ui_img_powerdot_png, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Menu1_screen_destroy(void)
{
    if(ui_Menu1) lv_obj_del(ui_Menu1);

    // NULL screen variables
    ui_Menu1 = NULL;
    ui_MenuPrev = NULL;
    ui_MenuPrevRoller = NULL;
    ui_MenuActive = NULL;
    ui_MenuActiveRoller = NULL;
    ui_MenuNext = NULL;
    ui_MenuNextRoller = NULL;
    ui_ButtonIcons2 = NULL;
    ui_Button9 = NULL;
    ui_Button5 = NULL;
    ui_Button6 = NULL;
    ui_Button7 = NULL;

}
