// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Roasting = NULL;
lv_obj_t * ui_BrewStyleVariable1 = NULL;
lv_obj_t * ui_IntensityVariable2 = NULL;
lv_obj_t * ui_RoasterStatus = NULL;
lv_obj_t * ui_TimeRemaining = NULL;
lv_obj_t * ui_ButtonIcons1 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_ReadyTitle4 = NULL;
lv_obj_t * ui_Arc1 = NULL;
// event funtions
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 10, 0, &ui_Menu1_screen_init);
    }
}

// build funtions

void ui_Roasting_screen_init(void)
{
    ui_Roasting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Roasting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Roasting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roasting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewStyleVariable1 = lv_label_create(ui_Roasting);
    lv_obj_set_width(ui_BrewStyleVariable1, 500);
    lv_obj_set_height(ui_BrewStyleVariable1, 48);
    lv_obj_set_x(ui_BrewStyleVariable1, 50);
    lv_obj_set_y(ui_BrewStyleVariable1, -157);
    lv_obj_set_align(ui_BrewStyleVariable1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BrewStyleVariable1, "Style_Variable");
    lv_obj_clear_flag(ui_BrewStyleVariable1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_BrewStyleVariable1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_BrewStyleVariable1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrewStyleVariable1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BrewStyleVariable1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewStyleVariable1, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntensityVariable2 = lv_label_create(ui_Roasting);
    lv_obj_set_width(ui_IntensityVariable2, 500);
    lv_obj_set_height(ui_IntensityVariable2, 48);
    lv_obj_set_x(ui_IntensityVariable2, 50);
    lv_obj_set_y(ui_IntensityVariable2, -97);
    lv_obj_set_align(ui_IntensityVariable2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_IntensityVariable2, "Intensity_Variable");
    lv_obj_set_style_text_color(ui_IntensityVariable2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IntensityVariable2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IntensityVariable2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IntensityVariable2, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoasterStatus = lv_label_create(ui_Roasting);
    lv_obj_set_width(ui_RoasterStatus, 287);
    lv_obj_set_height(ui_RoasterStatus, 75);
    lv_obj_set_x(ui_RoasterStatus, 52);
    lv_obj_set_y(ui_RoasterStatus, 25);
    lv_obj_set_align(ui_RoasterStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_RoasterStatus, "Roasting...");
    lv_obj_set_style_text_align(ui_RoasterStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RoasterStatus, &ui_font_BigText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeRemaining = lv_label_create(ui_Roasting);
    lv_obj_set_width(ui_TimeRemaining, 287);
    lv_obj_set_height(ui_TimeRemaining, 75);
    lv_obj_set_x(ui_TimeRemaining, 52);
    lv_obj_set_y(ui_TimeRemaining, 85);
    lv_obj_set_align(ui_TimeRemaining, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeRemaining, "1:30");
    lv_obj_set_style_text_align(ui_TimeRemaining, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeRemaining, &ui_font_BigText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIcons1 = lv_obj_create(ui_Roasting);
    lv_obj_remove_style_all(ui_ButtonIcons1);
    lv_obj_set_width(ui_ButtonIcons1, 800);
    lv_obj_set_height(ui_ButtonIcons1, 60);
    lv_obj_set_align(ui_ButtonIcons1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ButtonIcons1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonIcons1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ButtonIcons1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button8 = lv_btn_create(ui_ButtonIcons1);
    lv_obj_set_width(ui_Button8, 50);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button8, &ui_img_dimmuburger_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_ButtonIcons1);
    lv_obj_set_width(ui_Button10, 50);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_ButtonIcons1);
    lv_obj_set_width(ui_Button11, 50);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_ButtonIcons1);
    lv_obj_set_width(ui_Button12, 50);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x030101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button12, &ui_img_powerstop_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyTitle4 = lv_label_create(ui_Roasting);
    lv_obj_set_width(ui_ReadyTitle4, 190);
    lv_obj_set_height(ui_ReadyTitle4, 137);
    lv_obj_set_x(ui_ReadyTitle4, 253);
    lv_obj_set_y(ui_ReadyTitle4, 350);
    lv_obj_set_align(ui_ReadyTitle4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ReadyTitle4, "Stop");
    lv_obj_set_style_text_color(ui_ReadyTitle4, lv_color_hex(0xE66918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadyTitle4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ReadyTitle4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadyTitle4, &ui_font_BigText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Roasting);
    lv_obj_set_width(ui_Arc1, 125);
    lv_obj_set_height(ui_Arc1, 125);
    lv_obj_set_x(ui_Arc1, 253);
    lv_obj_set_y(ui_Arc1, 25);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);
    lv_arc_set_bg_angles(ui_Arc1, 270, 268);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xE66918), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);

}

void ui_Roasting_screen_destroy(void)
{
    if(ui_Roasting) lv_obj_del(ui_Roasting);

    // NULL screen variables
    ui_Roasting = NULL;
    ui_BrewStyleVariable1 = NULL;
    ui_IntensityVariable2 = NULL;
    ui_RoasterStatus = NULL;
    ui_TimeRemaining = NULL;
    ui_ButtonIcons1 = NULL;
    ui_Button8 = NULL;
    ui_Button10 = NULL;
    ui_Button11 = NULL;
    ui_Button12 = NULL;
    ui_ReadyTitle4 = NULL;
    ui_Arc1 = NULL;

}
