// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ROASTMAIN_H
#define UI_ROASTMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RoastMain
extern void ui_RoastMain_screen_init(void);
extern void ui_RoastMain_screen_destroy(void);
extern lv_obj_t * ui_RoastMain;
extern lv_obj_t * ui_BrewingStyle;
extern lv_obj_t * ui_Intensity;
extern lv_obj_t * ui_BrewStyleVariable;
extern lv_obj_t * ui_IntensityVariable1;
extern lv_obj_t * ui_ReadyTitle;
extern lv_obj_t * ui_ReadyTitle1;
extern lv_obj_t * ui_ButtonIcons;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

