// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ROASTING_H
#define UI_ROASTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Roasting
extern void ui_Roasting_screen_init(void);
extern void ui_Roasting_screen_destroy(void);
extern lv_obj_t * ui_Roasting;
extern lv_obj_t * ui_BrewStyleVariable1;
extern lv_obj_t * ui_IntensityVariable2;
extern lv_obj_t * ui_RoasterStatus;
extern lv_obj_t * ui_TimeRemaining;
extern lv_obj_t * ui_ButtonIcons1;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_ReadyTitle4;
extern lv_obj_t * ui_Arc1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

