// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_RoastMain = NULL;
lv_obj_t * ui_BrewingStyle = NULL;
lv_obj_t * ui_Intensity = NULL;
lv_obj_t * ui_BrewStyleVariable = NULL;
lv_obj_t * ui_IntensityVariable1 = NULL;
lv_obj_t * ui_ReadyTitle = NULL;
lv_obj_t * ui_ReadyTitle1 = NULL;
lv_obj_t * ui_ButtonIcons = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button4 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 10, 0, &ui_Menu1_screen_init);
    }
}

// build funtions

void ui_RoastMain_screen_init(void)
{
    ui_RoastMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RoastMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RoastMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoastMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewingStyle = lv_label_create(ui_RoastMain);
    lv_obj_set_width(ui_BrewingStyle, 500);
    lv_obj_set_height(ui_BrewingStyle, 48);
    lv_obj_set_x(ui_BrewingStyle, -278);
    lv_obj_set_y(ui_BrewingStyle, -161);
    lv_obj_set_align(ui_BrewingStyle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewingStyle, "Brewing Style");
    lv_obj_set_style_text_color(ui_BrewingStyle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrewingStyle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BrewingStyle, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewingStyle, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Intensity = lv_label_create(ui_RoastMain);
    lv_obj_set_width(ui_Intensity, 500);
    lv_obj_set_height(ui_Intensity, 48);
    lv_obj_set_x(ui_Intensity, -287);
    lv_obj_set_y(ui_Intensity, -95);
    lv_obj_set_align(ui_Intensity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Intensity, "Intensity");
    lv_obj_set_style_text_color(ui_Intensity, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Intensity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Intensity, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Intensity, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewStyleVariable = lv_label_create(ui_RoastMain);
    lv_obj_set_width(ui_BrewStyleVariable, 500);
    lv_obj_set_height(ui_BrewStyleVariable, 48);
    lv_obj_set_x(ui_BrewStyleVariable, 257);
    lv_obj_set_y(ui_BrewStyleVariable, -161);
    lv_obj_set_align(ui_BrewStyleVariable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewStyleVariable, "Style_Variable");
    lv_obj_clear_flag(ui_BrewStyleVariable,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_BrewStyleVariable, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_BrewStyleVariable, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewStyleVariable, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntensityVariable1 = lv_label_create(ui_RoastMain);
    lv_obj_set_width(ui_IntensityVariable1, 500);
    lv_obj_set_height(ui_IntensityVariable1, 48);
    lv_obj_set_x(ui_IntensityVariable1, 258);
    lv_obj_set_y(ui_IntensityVariable1, -97);
    lv_obj_set_align(ui_IntensityVariable1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IntensityVariable1, "Intensity_Variable");
    lv_obj_set_style_text_align(ui_IntensityVariable1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IntensityVariable1, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyTitle = lv_label_create(ui_RoastMain);
    lv_obj_set_width(ui_ReadyTitle, 282);
    lv_obj_set_height(ui_ReadyTitle, 137);
    lv_obj_set_x(ui_ReadyTitle, 37);
    lv_obj_set_y(ui_ReadyTitle, 152);
    lv_obj_set_align(ui_ReadyTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReadyTitle, "Ready to");
    lv_obj_set_style_text_align(ui_ReadyTitle, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadyTitle, &ui_font_BigText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReadyTitle1 = lv_label_create(ui_RoastMain);
    lv_obj_set_width(ui_ReadyTitle1, 500);
    lv_obj_set_height(ui_ReadyTitle1, 137);
    lv_obj_set_x(ui_ReadyTitle1, 437);
    lv_obj_set_y(ui_ReadyTitle1, 152);
    lv_obj_set_align(ui_ReadyTitle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReadyTitle1, "roast.");
    lv_obj_set_style_text_color(ui_ReadyTitle1, lv_color_hex(0xE66918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReadyTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ReadyTitle1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReadyTitle1, &ui_font_BigText, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIcons = lv_obj_create(ui_RoastMain);
    lv_obj_remove_style_all(ui_ButtonIcons);
    lv_obj_set_width(ui_ButtonIcons, 800);
    lv_obj_set_height(ui_ButtonIcons, 60);
    lv_obj_set_align(ui_ButtonIcons, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ButtonIcons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonIcons, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ButtonIcons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_ButtonIcons);
    lv_obj_set_width(ui_Button1, 50);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_dimmuburger_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_ButtonIcons);
    lv_obj_set_width(ui_Button2, 50);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_ButtonIcons);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_ButtonIcons);
    lv_obj_set_width(ui_Button4, 50);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x030101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button4, &ui_img_powerdot_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_RoastMain_screen_destroy(void)
{
    if(ui_RoastMain) lv_obj_del(ui_RoastMain);

    // NULL screen variables
    ui_RoastMain = NULL;
    ui_BrewingStyle = NULL;
    ui_Intensity = NULL;
    ui_BrewStyleVariable = NULL;
    ui_IntensityVariable1 = NULL;
    ui_ReadyTitle = NULL;
    ui_ReadyTitle1 = NULL;
    ui_ButtonIcons = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;
    ui_Button3 = NULL;
    ui_Button4 = NULL;

}
