// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_logoblack;
lv_obj_t * ui_SplashScreen = NULL;
lv_obj_t * ui_logoblack = NULL;
// event funtions

// build funtions

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoblack = lv_img_create(ui_SplashScreen);
    lv_img_set_src(ui_logoblack, &ui_img_logoblack_png);
    lv_obj_set_width(ui_logoblack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logoblack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_logoblack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logoblack, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logoblack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_logoblack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_logoblack = ui_logoblack;

}

void ui_SplashScreen_screen_destroy(void)
{
    if(ui_SplashScreen) lv_obj_del(ui_SplashScreen);

    // NULL screen variables
    ui_SplashScreen = NULL;
    uic_logoblack = NULL;
    ui_logoblack = NULL;

}
