// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SplashScreen.h"
#include "screens/ui_RoastMain.h"
#include "screens/ui_Menu1.h"
#include "screens/ui_Roasting.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * ShiftMenuLeft_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShiftMenuRight_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logoblack_png);    // assets/logoblack.png
LV_IMG_DECLARE(ui_img_dimmuburger_png);    // assets/DimmuBurger.png
LV_IMG_DECLARE(ui_img_powerdot_png);    // assets/PowerDot.png
LV_IMG_DECLARE(ui_img_arrowup_png);    // assets/ArrowUp.png
LV_IMG_DECLARE(ui_img_arrowdown_png);    // assets/ArrowDown.png
LV_IMG_DECLARE(ui_img_backarrow_png);    // assets/BackArrow.png
LV_IMG_DECLARE(ui_img_powerstop_png);    // assets/PowerStop.png

// FONTS
LV_FONT_DECLARE(ui_font_BigText);
LV_FONT_DECLARE(ui_font_Bold);
LV_FONT_DECLARE(ui_font_MenuSmall);
LV_FONT_DECLARE(ui_font_Reg32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
